# -*- coding: utf-8 -*-
"""OŁ JEA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZI2afI4SK1eKfq4vfiW9WRfJbSjNkHp7
"""

import pandas as pd
import numpy as np
import re

def readFile(path):
    main_file = pd.DataFrame(open(path, "r").readlines(), columns=['Record'])
    return main_file


def extract_and_validate_order_numbers(df: pd.DataFrame) -> pd.DataFrame:
    # Ekstrakcja numerów porządkowych z początku wierszy
    df['OrderNumber'] = df['Record'].str.extract(r'^(\d{1,5})').astype(float)

    # Inicjalizacja kolumny do sprawdzenia poprawności kolejności
    df['ValidOrder'] = True

    last_valid_order = None
    for index, row in df.iterrows():
        if pd.isna(row['OrderNumber']):
            continue  # Pominięcie wierszy bez numeru porządkowego
        if last_valid_order is None:
            last_valid_order = row['OrderNumber']
        elif 0 < row['OrderNumber'] - last_valid_order <= 5:
            last_valid_order = row['OrderNumber']
        else:
            df.at[index, 'ValidOrder'] = False  # Oznaczenie niepoprawnej kolejności
            df.at[index, 'OrderNumber'] = np.nan  # Usunięcie niepoprawnego numeru porządkowego

    return df

# Przykładowe wywołanie funkcji
path = '/content/1972(2).txt'  # Zastąp 'ścieżka_do_pliku.txt' rzeczywistą ścieżką do pliku
df = readFile(path)
df_validated = extract_and_validate_order_numbers(df)

df_validated